extends Resource
class_name HudStyle
## One place to tune the UI's look: palette, type, and the shared styleboxes.
##
## The look is a storybook satchel: parchment sheets in carved walnut frames, torn paper notes,
## leather tabs, bone key caps, wooden plaque buttons and brass for focus. The textures are
## generated by tools/ui/make_ui_textures.py into assets/ui/ and used here as StyleBoxTexture
## nine-patches (the margins below match the generator). Text on paper is ink (`text`,
## `text_soft`, `accent`); text drawn straight over the world uses `light` / `light_soft`;
## text on wood or leather uses `on_wood`. Every panel builds from these, and
## assets/ui/woods_theme.tres (tools/ui/build_theme.gd) makes plain Controls match.

## Ink on paper: body text and headings.
@export var text: Color = Color("3a2a1c")
## Ink on paper: secondary lines, captions, footers.
@export var text_soft: Color = Color("6b5540")
## Rust ink on paper: counts, highlights, the active thing.
@export var accent: Color = Color("97461f")
## Moss ink on paper: "enough", done, good news.
@export var good: Color = Color("4d6b2c")
## Cream text over the world (place card, rest line, signpost line), with a dark halo.
@export var light: Color = Color("f6ecd6")
@export var light_soft: Color = Color(0.965, 0.93, 0.85, 0.9)
## Warm gold over the world (the place card rule, fireflies on the title).
@export var gold: Color = Color("e3bf73")
## Cream text on wood and leather (buttons, active tabs, the speaker ribbon).
@export var on_wood: Color = Color("f5e6c4")
@export var shadow: Color = Color(0.08, 0.05, 0.03, 0.6)
## Faint paper highlight under ink: a letterpress feel instead of a drop shadow.
@export var emboss: Color = Color(1.0, 0.97, 0.88, 0.45)
## The old dark pill (debug overlays only; the game UI is paper).
@export var pill: Color = Color(0.11, 0.086, 0.062, 0.58)
@export var key_text: Color = Color("3a2c1e")
@export var serif: Font = preload("res://assets/fonts/Fraunces-Variable.ttf")
@export var sans: Font = preload("res://assets/fonts/Nunito-Variable.ttf")

const UI_DIR := "res://assets/ui/"
const COIN_ICON_PATH := "res://assets/ui/coin.svg"
## Menu rows, action buttons and tabs share these heights (design §26: consistent button sizes).
const MENU_ROW_H := 34
const ACTION_H := 30
const TAB_H := 32

var _cache: Dictionary = {}


func font(kind: StringName, weight: int, optical: int = 0) -> Font:
	var key := "%s_%d_%d" % [kind, weight, optical]
	if _cache.has(key):
		return _cache[key]
	var ts := TextServerManager.get_primary_interface()
	var fv := FontVariation.new()
	fv.base_font = serif if kind == &"serif" else sans
	var axes := {ts.name_to_tag("wght"): weight}
	if kind == &"serif":
		axes[ts.name_to_tag("opsz")] = optical if optical > 0 else 36
		axes[ts.name_to_tag("SOFT")] = 100
		axes[ts.name_to_tag("WONK")] = 1
	fv.variation_opentype = axes
	_cache[key] = fv
	return fv


## Font, size and colour. Dark (ink) colours get a faint paper emboss below; light colours get a
## soft dark halo so they read over the world. shadow_px 0 = no shadow at all.
func label(l: Label, kind: StringName, weight: int, size: int, color: Color, shadow_px: int = 2) -> void:
	l.add_theme_font_override("font", font(kind, weight, size * 2 if kind == &"serif" else 0))
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", color)
	var ink := color.get_luminance() < 0.5
	l.add_theme_color_override("font_shadow_color", emboss if ink else shadow)
	l.add_theme_constant_override("shadow_offset_x", 0)
	l.add_theme_constant_override("shadow_offset_y", (1 if ink else shadow_px) if shadow_px > 0 else 0)
	l.add_theme_constant_override("shadow_outline_size", 0 if ink or shadow_px <= 0 else 4)


# ---------------------------------------------------------------- textures and nine-patches

func tex(name: String) -> Texture2D:
	var key := "tex_" + name
	if not _cache.has(key):
		_cache[key] = load(UI_DIR + name + ".png") as Texture2D
	return _cache[key]


## A StyleBoxTexture over assets/ui/<name>.png. `margin` = texture margins (l, t, r, b),
## `content` = content margins, `expand` = how far the texture reaches outside the control
## (the baked drop-shadow padding, so the visible edge sits on the control's rect).
func nine(name: String, margin: Vector4, content: Vector4, expand: float = 0.0, stretch: int = StyleBoxTexture.AXIS_STRETCH_MODE_STRETCH) -> StyleBoxTexture:
	var sb := StyleBoxTexture.new()
	sb.texture = tex(name)
	sb.texture_margin_left = margin.x
	sb.texture_margin_top = margin.y
	sb.texture_margin_right = margin.z
	sb.texture_margin_bottom = margin.w
	sb.content_margin_left = content.x
	sb.content_margin_top = content.y
	sb.content_margin_right = content.z
	sb.content_margin_bottom = content.w
	if expand > 0.0:
		sb.expand_margin_left = expand
		sb.expand_margin_top = expand
		sb.expand_margin_right = expand
		sb.expand_margin_bottom = expand
	sb.axis_stretch_horizontal = stretch
	sb.axis_stretch_vertical = stretch
	return sb


## Modal panels (pause menu, satchel, shop, journal, ...): parchment in a carved walnut frame.
func panel_box() -> StyleBoxTexture:
	return nine("panel_frame", Vector4(46, 46, 46, 46), Vector4(44, 36, 44, 34), 10.0)


## A loose torn sheet: dialogue, the fishing card.
func paper_box() -> StyleBoxTexture:
	return nine("panel_paper", Vector4(34, 34, 34, 34), Vector4(26, 18, 26, 18), 12.0)


## A small pinned note (the HUD's request, the compass): torn edge and a faint ruled border.
func note_box() -> StyleBoxTexture:
	return nine("paper_note", Vector4(24, 24, 24, 24), Vector4(16, 10, 16, 11), 8.0)


## A scrap of paper for small HUD things (pickup toasts, the prompt, the purse, cost chips).
func chip_box() -> StyleBoxTexture:
	return nine("paper_small", Vector4(16, 16, 16, 16), Vector4(10, 5, 13, 6), 6.0)


## The old dark pill, kept for debug overlays (PerfOverlay). The game UI uses paper.
func pill_box() -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = pill
	sb.set_corner_radius_all(16)
	sb.content_margin_left = 8
	sb.content_margin_right = 14
	sb.content_margin_top = 5
	sb.content_margin_bottom = 5
	sb.shadow_color = Color(0, 0, 0, 0.16)
	sb.shadow_size = 8
	sb.anti_aliasing = true
	return sb


## A card pressed into the page for list rows (shop, chest, cooking). hover = warmer paper.
func row_box(hover: bool = false) -> StyleBoxTexture:
	return nine("row_card_hover" if hover else "row_card", Vector4(14, 14, 14, 14), Vector4(10, 6, 10, 6))


## Brass focus ring drawn over a row card or action button.
func focus_box() -> StyleBoxTexture:
	return nine("focus_ring", Vector4(12, 12, 12, 12), Vector4(10, 6, 10, 6), 2.0)


func key_box(pressed: bool) -> StyleBoxTexture:
	var sb := nine("keycap_pressed" if pressed else "keycap", Vector4(10, 10, 10, 11), Vector4(7, 2 if not pressed else 4, 7, 4))
	return sb


## Satchel / journal slot: `state` is &"normal", &"hover" or &"focus" (focus is the brass
## ring alone; Button draws it over the normal box).
func slot_box(state: StringName = &"normal") -> StyleBoxTexture:
	match state:
		&"hover":
			return nine("slot_hover", Vector4(16, 16, 16, 16), Vector4(4, 4, 4, 4))
		&"focus":
			return nine("slot_focus", Vector4(16, 16, 16, 16), Vector4(4, 4, 4, 4), 1.0)
	return nine("slot", Vector4(16, 16, 16, 16), Vector4(4, 4, 4, 4))


## Styles a Button as a slot (normal / hover / pressed / focus).
func style_slot(b: Button) -> void:
	b.add_theme_stylebox_override("normal", slot_box(&"normal"))
	b.add_theme_stylebox_override("hover", slot_box(&"hover"))
	b.add_theme_stylebox_override("pressed", slot_box(&"hover"))
	b.add_theme_stylebox_override("hover_pressed", slot_box(&"hover"))
	b.add_theme_stylebox_override("disabled", slot_box(&"normal"))
	b.add_theme_stylebox_override("focus", slot_box(&"focus"))


## A rarity rim for a slot (uncommon and up): a tinted ring just inside the inked edge.
## Add it as the slot's first child; set_rarity_rim() recolours or hides it.
func rarity_rim(r: int) -> NinePatchRect:
	var n := NinePatchRect.new()
	n.name = "Rim"
	n.texture = tex("slot_rim")
	n.patch_margin_left = 16
	n.patch_margin_top = 16
	n.patch_margin_right = 16
	n.patch_margin_bottom = 16
	n.set_anchors_preset(Control.PRESET_FULL_RECT)
	n.mouse_filter = Control.MOUSE_FILTER_IGNORE
	set_rarity_rim(n, r)
	return n


static func set_rarity_rim(n: NinePatchRect, r: int) -> void:
	n.visible = r > 0
	n.self_modulate = Color(rarity_color(r), 0.85)


func bar_track_box() -> StyleBoxTexture:
	return nine("bar_track", Vector4(7, 7, 7, 7), Vector4(0, 0, 0, 0))


func bar_fill_box() -> StyleBoxTexture:
	return nine("bar_fill", Vector4(7, 7, 7, 7), Vector4(0, 0, 0, 0))


## Styles a ProgressBar as an inked groove with an amber fill.
func style_bar(bar: ProgressBar) -> void:
	bar.add_theme_stylebox_override("background", bar_track_box())
	bar.add_theme_stylebox_override("fill", bar_fill_box())


## Styles an HSlider: inked groove, amber fill up to a brass knob.
func style_slider(s: HSlider) -> void:
	var track := bar_track_box()
	track.content_margin_top = 5
	track.content_margin_bottom = 5
	var fill := bar_fill_box()
	fill.content_margin_top = 5
	fill.content_margin_bottom = 5
	s.add_theme_stylebox_override("slider", track)
	s.add_theme_stylebox_override("grabber_area", fill)
	s.add_theme_stylebox_override("grabber_area_highlight", fill)
	s.add_theme_icon_override("grabber", tex("knob"))
	s.add_theme_icon_override("grabber_highlight", tex("knob_hot"))
	s.add_theme_icon_override("grabber_disabled", tex("knob"))


# ---------------------------------------------------------------- page furniture

## An inked divider with a small rust diamond in the middle. `margin` = space above / below.
func rule(top: int = 10, bottom: int = 8) -> MarginContainer:
	var m := MarginContainer.new()
	m.add_theme_constant_override("margin_top", top)
	m.add_theme_constant_override("margin_bottom", bottom)
	m.mouse_filter = Control.MOUSE_FILTER_IGNORE
	var h := HBoxContainer.new()
	h.add_theme_constant_override("separation", 2)
	h.mouse_filter = Control.MOUSE_FILTER_IGNORE
	m.add_child(h)
	for i in 3:
		var t := TextureRect.new()
		t.mouse_filter = Control.MOUSE_FILTER_IGNORE
		t.size_flags_vertical = Control.SIZE_SHRINK_CENTER
		if i == 1:
			t.texture = tex("rule_ornament")
			t.custom_minimum_size = Vector2(28, 14)
			t.stretch_mode = TextureRect.STRETCH_KEEP_CENTERED
		else:
			t.texture = tex("rule_line")
			t.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
			t.stretch_mode = TextureRect.STRETCH_SCALE
			t.custom_minimum_size = Vector2(24, 8)
			t.size_flags_horizontal = Control.SIZE_EXPAND_FILL
			t.flip_h = i == 2
		h.add_child(t)
	return m


## A red wax seal (quest notes, the map's cartouche, the title card).
func seal(px: int = 34) -> TextureRect:
	var t := TextureRect.new()
	t.texture = tex("seal")
	t.custom_minimum_size = Vector2(px, px)
	t.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	t.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	t.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return t


## The speaker's cloth ribbon (dialogue): swallowtail ends, cream text.
func ribbon_box() -> StyleBoxTexture:
	return nine("ribbon", Vector4(20, 8, 20, 8), Vector4(20, 2, 20, 4))


## The compass band: a short parchment strip with rolled ends.
func band_box() -> StyleBoxTexture:
	return nine("scroll_band", Vector4(26, 12, 26, 12), Vector4(24, 4, 24, 4))


## Dims the world behind a modal panel: a warm wash plus a vignette. Added to `root` first.
func add_backdrop(root: Control, strength: float = 0.42) -> void:
	var dim := ColorRect.new()
	dim.name = "Dim"
	dim.color = Color(0.09, 0.055, 0.03, strength)
	dim.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.add_child(dim)
	var vig := TextureRect.new()
	vig.name = "Vignette"
	vig.texture = tex("vignette")
	vig.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	vig.stretch_mode = TextureRect.STRETCH_SCALE
	vig.set_anchors_preset(Control.PRESET_FULL_RECT)
	vig.mouse_filter = Control.MOUSE_FILTER_IGNORE
	vig.modulate.a = 0.75
	root.add_child(vig)


## A panel heading: Fraunces title (and an optional rust sub-heading), optionally with a seal.
func heading(parent: Control, title_text: String, size: int = 34) -> Label:
	var t := Label.new()
	t.text = title_text
	label(t, &"serif", 600, size, text, 1)
	parent.add_child(t)
	return t


## Footer hint: key caps then a soft label ("Esc  Close").
func add_hint(parent: Control, keys: Array, text_: String, gap_after: int = 10) -> void:
	for k: String in keys:
		parent.add_child(KeyCap.new().setup(self, k))
	var l := Label.new()
	l.text = text_
	label(l, &"sans", 650, 13, text_soft, 0)
	parent.add_child(l)
	if gap_after > 0:
		var gap := Control.new()
		gap.custom_minimum_size = Vector2(gap_after, 0)
		parent.add_child(gap)


# ---------------------------------------------------------------- item rarity (ItemDef.rarity)

const RARITY_NAMES: PackedStringArray = ["Common", "Uncommon", "Rare", "Epic", "Legendary"]
## Inks that read on parchment: sepia, moss, lake blue, heather, amber-gold.
const RARITY_COLORS: Array[Color] = [
	Color("4a3726"), Color("4f7a2e"), Color("2e6a93"), Color("7c4596"), Color("a86f0c"),
]
## The same, light enough to sit over the world (cream, sage, lake, heather, amber).
const RARITY_LIGHT: Array[Color] = [
	Color("e6dcc6"), Color("a9c98a"), Color("8fbcd6"), Color("c4a3d8"), Color("f0c46a"),
]


static func rarity_name(r: int) -> String:
	return RARITY_NAMES[clampi(r, 0, RARITY_NAMES.size() - 1)]


static func rarity_color(r: int) -> Color:
	return RARITY_COLORS[clampi(r, 0, RARITY_COLORS.size() - 1)]


static func rarity_light(r: int) -> Color:
	return RARITY_LIGHT[clampi(r, 0, RARITY_LIGHT.size() - 1)]


# ---------------------------------------------------------------- tabs and buttons

## A leather tab (satchel filters, shop Sell / Buy): dark leather with cream text when
## active, a faded paper tab with ink text when not.
func tab_button(text_: String) -> Button:
	var b := Button.new()
	b.text = text_
	b.focus_mode = Control.FOCUS_ALL
	b.toggle_mode = true
	b.custom_minimum_size = Vector2(0, TAB_H)
	b.add_theme_font_override("font", font(&"serif", 600, 28))
	b.add_theme_font_size_override("font_size", 15)
	set_tab_active(b, false)
	return b


func set_tab_active(b: Button, on: bool) -> void:
	b.set_pressed_no_signal(on)
	var c := on_wood if on else text_soft
	for state: String in ["font_color", "font_hover_color", "font_focus_color", "font_pressed_color", "font_hover_pressed_color"]:
		b.add_theme_color_override(state, c if on or state == "font_color" else text)
	var box := _tab_box(on)
	b.add_theme_stylebox_override("normal", box)
	b.add_theme_stylebox_override("pressed", box)
	b.add_theme_stylebox_override("hover", box if on else _tab_box(false, true))
	b.add_theme_stylebox_override("hover_pressed", box)
	var focus := focus_box()
	focus.expand_margin_bottom = 0
	b.add_theme_stylebox_override("focus", focus)


func _tab_box(on: bool, hover: bool = false) -> StyleBoxTexture:
	var sb := nine("tab_on" if on else "tab_off", Vector4(12, 12, 12, 4), Vector4(14, 4, 14, 5))
	if hover:
		sb.modulate_color = Color(1.06, 1.03, 0.97)
	return sb


## A small carved wooden plaque button (Sell 1, Buy, Repair): cream text, brass ring on focus.
func action_button(text_: String) -> Button:
	var b := Button.new()
	b.text = text_
	b.focus_mode = Control.FOCUS_ALL
	b.custom_minimum_size = Vector2(0, ACTION_H)
	b.add_theme_font_override("font", font(&"sans", 800))
	b.add_theme_font_size_override("font_size", 13)
	for state: String in ["font_color", "font_hover_color", "font_pressed_color", "font_focus_color", "font_hover_pressed_color"]:
		b.add_theme_color_override(state, on_wood)
	b.add_theme_color_override("font_disabled_color", Color(on_wood, 0.55))
	b.add_theme_color_override("font_outline_color", Color(0.16, 0.09, 0.04, 0.5))
	b.add_theme_constant_override("outline_size", 2)
	b.add_theme_stylebox_override("normal", _wood_box("button_wood"))
	b.add_theme_stylebox_override("hover", _wood_box("button_wood_hover"))
	b.add_theme_stylebox_override("pressed", _wood_box("button_wood_pressed", 1))
	b.add_theme_stylebox_override("hover_pressed", _wood_box("button_wood_pressed", 1))
	b.add_theme_stylebox_override("disabled", _wood_box("button_wood_disabled"))
	b.add_theme_stylebox_override("focus", focus_box())
	return b


func _wood_box(name: String, dip: int = 0) -> StyleBoxTexture:
	return nine(name, Vector4(12, 12, 12, 14), Vector4(13, 3 + dip, 13, 6 - dip))


## A signpost plank (the title menu): the wooden plaque at menu size, serif lettering.
func style_plank_button(b: Button) -> void:
	b.focus_mode = Control.FOCUS_ALL
	b.custom_minimum_size = Vector2(236, 44)
	b.add_theme_font_override("font", font(&"serif", 600, 38))
	b.add_theme_font_size_override("font_size", 19)
	for state: String in ["font_color", "font_hover_color", "font_pressed_color", "font_focus_color", "font_hover_pressed_color"]:
		b.add_theme_color_override(state, on_wood)
	b.add_theme_color_override("font_outline_color", Color(0.16, 0.09, 0.04, 0.6))
	b.add_theme_constant_override("outline_size", 3)
	b.add_theme_stylebox_override("normal", _wood_box("button_wood"))
	b.add_theme_stylebox_override("hover", _wood_box("button_wood_hover"))
	b.add_theme_stylebox_override("pressed", _wood_box("button_wood_pressed", 1))
	b.add_theme_stylebox_override("hover_pressed", _wood_box("button_wood_pressed", 1))
	b.add_theme_stylebox_override("disabled", _wood_box("button_wood_disabled"))
	b.add_theme_stylebox_override("focus", focus_box())


## A menu row on paper (pause menu, title, settings): ink text, an ink-wash on hover and a
## rust diamond + wash on focus. All states keep the same margins so text never shifts.
func style_menu_button(b: Button) -> void:
	b.custom_minimum_size.y = MENU_ROW_H
	b.add_theme_font_override("font", font(&"serif", 560, 32))
	b.add_theme_font_size_override("font_size", 17)
	for state: String in ["font_color", "font_pressed_color", "font_hover_pressed_color"]:
		b.add_theme_color_override(state, text)
	b.add_theme_color_override("font_hover_color", text)
	b.add_theme_color_override("font_focus_color", accent)
	b.add_theme_color_override("font_disabled_color", Color(text_soft, 0.45))
	var pad := Vector4(26, 4, 14, 5)
	var empty := StyleBoxEmpty.new()
	empty.content_margin_left = pad.x
	empty.content_margin_top = pad.y
	empty.content_margin_right = pad.z
	empty.content_margin_bottom = pad.w
	b.add_theme_stylebox_override("normal", empty)
	b.add_theme_stylebox_override("disabled", empty)
	b.add_theme_stylebox_override("hover", nine("row_hover", Vector4(20, 8, 20, 8), pad))
	b.add_theme_stylebox_override("pressed", nine("row_focus", Vector4(24, 8, 20, 8), pad))
	b.add_theme_stylebox_override("hover_pressed", nine("row_focus", Vector4(24, 8, 20, 8), pad))
	b.add_theme_stylebox_override("focus", nine("row_focus", Vector4(24, 8, 20, 8), pad))


## Coin icon + amount, for the HUD purse and the shop header / prices.
func coin_label(parent: Control, amount: int, size: int = 14, icon_px: int = 18) -> Label:
	var h := HBoxContainer.new()
	h.add_theme_constant_override("separation", 4)
	h.mouse_filter = Control.MOUSE_FILTER_IGNORE
	parent.add_child(h)
	var icon := TextureRect.new()
	icon.texture = load(COIN_ICON_PATH) as Texture2D
	icon.custom_minimum_size = Vector2(icon_px, icon_px)
	icon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	icon.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	icon.mouse_filter = Control.MOUSE_FILTER_IGNORE
	h.add_child(icon)
	var l := Label.new()
	l.text = str(amount)
	l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	label(l, &"sans", 800, size, text, 1)
	h.add_child(l)
	return l
